name: Backend Deployment

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

env:
  ECR_REGISTRY: 257394484725.dkr.ecr.eu-north-1.amazonaws.com
  ECR_REPOSITORY: pet-ai-backend
  AWS_REGION: eu-north-1

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Anasmtaweh/pet-ai-project
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Get ECR password
        id: ecr-password
        run: |
          PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)
          echo "ECR_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "::add-mask::$PASSWORD"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.60.74.169
          port: 2222
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "${{ env.ECR_PASSWORD }}" | docker login --username AWS --password-stdin $ECR_REGISTRY
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker stop backend-container || true
            docker rm backend-container || true
            docker run -d \
              --name backend-container \
              -p 3001:3001 \
              -e NODE_ENV=production \
              $ECR_REGISTRY/$ECR_REPOSITORY:latest